#!/bin/bash
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

BINREPO=$HOME/binrepo
CCACHE_SIZE=10G


echo "==== Setting up environment ===="
set -e
COMMIT=$1
REPO=$2
PLATFORM=$3
BUILDER=$4
export BUILDER_HOME=`readlink -f $5`
echo "building commit $COMMIT from repo $REPO in workdir $BUILDER_HOME on platform $PLATFORM as builder $BUILDER with script $0."
cd $BUILDER_HOME
rm -rf builddir artifactdir
mkdir -p builddir tarballs ccache
export CCACHE_DIR=$BUILDER_HOME/ccache
export BINREPO_BRANCH=builder-$BUILDER
export BINREPO_TAG=source-hash-$COMMIT
(cd $BINREPO && git branch $BINREPO_BRANCH initial) || true
git clone $BINREPO $BUILDER_HOME/artifactdir --branch $BINREPO_BRANCH
(cd $BUILDER_HOME/artifactdir && git rm -r `git ls-tree --name-only HEAD`)
git --git-dir=$REPO log -1 --pretty=format:"source-hash-%H%n%n" $COMMIT > $BUILDER_HOME/commitmsg
git --git-dir=$REPO log -1 --pretty=fuller $COMMIT >> $BUILDER_HOME/commitmsg
ccache -M$CCACHE_SIZE
echo
echo

echo "==== Unpacking source ===="
echo Unpacking source ...
(cd $REPO && git archive --format tar $COMMIT)| tar --extract --directory $BUILDER_HOME/builddir
echo done.
mkdir -p $BUILDER_HOME/builddir/.git
echo
echo

echo "==== Configuring build ===="
echo "configuring commit $COMMIT from repo $REPO in workdir $BUILDER_HOME on platform $PLATFORM as builder $BUILDER with script $0." > $BUILDER_HOME/artifactdir/autogen.log
(cd $BUILDER_HOME/builddir && ./autogen.sh --with-external-tar=$BUILDER_HOME/tarballs --disable-linkoo --disable-option-checking --disable-dependency-tracking) 2>&1 | tee --append $BUILDER_HOME/artifactdir/autogen.log
echo
echo

echo "==== Building ===="
ccache -s
echo "building commit $COMMIT from repo $REPO in workdir $BUILDER_HOME on platform $PLATFORM as builder $BUILDER with script $0." > $BUILDER_HOME/artifactdir/make.log
echo "dev-installing commit $COMMIT from repo $REPO in workdir $BUILDER_HOME on platform $PLATFORM as builder $BUILDER with script $0." > $BUILDER_HOME/artifactdir/dev-install.log
(cd $BUILDER_HOME/builddir; make || make) 2>&1 | tee --append $BUILDER_HOME/artifactdir/make.log
(cd $BUILDER_HOME/builddir; make dev-install) 2>&1 | tee --append $BUILDER_HOME/artifactdir/dev-install.log
ccache -s
echo
echo

echo "==== Storing bibisect ===="
`grep DEVINSTALLDIR $BUILDER_HOME/builddir/config_host.mk`
echo archiving installation at $DEVINSTALLDIR ...
git --git-dir=$BUILDER_HOME/artifactdir/.git --work-tree=$DEVINSTALLDIR add -A
git --git-dir=$BUILDER_HOME/artifactdir/.git --work-tree=$DEVINSTALLDIR commit -F $BUILDER_HOME/commitmsg
git --git-dir=$BUILDER_HOME/artifactdir/.git tag $BINREPO_TAG || true
git --git-dir=$BUILDER_HOME/artifactdir/.git push origin $BINREPO_TAG:$BINREPO_TAG $BINREPO_BRANCH:$BINREPO_BRANCH
echo done.
echo
echo

# vim: set et sw=4 ts=4:
