#!/bin/bash

bin_dir="$(dirname $0)"
branch="master"
pull="yes"
push="no"
push_only="no"
src=$(pwd)
profile=${bin_dir}/build_profiles/en_us_rel.autogen
if [ -z "$DAILIES_LOG" ] ; then
	logfile=~/dailies.log
else
	logfile="$DAILIES_LOG"
fi

while [ "${1:-}" != "" ] ; do
	case $1 in
		--src) shift
			src="$1"
			;;
		-b|--branch) shift
			branch="$1"
			;;
		-p|--profile) shift
			profile="$1"
			;;
		--no-pull)
			pull="no"
			;;
		--pull)
			pull="yes";
			;;
		--push)
			push="yes"
			;;
		--push-only)
			push="yes"
            push_only="yes"
            pull="no"
			;;
		--no-push)
			push="no"
			;;
		--help)
			echo "$0 [--src <bootstrap git>] [-b|--branch <branch>] [-p|--profile <profile_file>] [--no-pull] [--push]"
			echo "    --src default to the current working dir"
			echo "    --branch default to master"
			echo "    --profile default to ${bin_dir}/build_profiles/en_us_rel.autogen"
			echo "    --pull and --no-push by default"
			exit 0
			;;
		-*)
			echo "Invalid option $1" 1>&2
			exit 1
			;;
		*)
			echo "extra argument $1" 1>&2
			exit 1;
			;;
	esac
	shift;
done

if [ ! -f ${profile} ] ; then
	if [ -f "${bin_dir}/build_profiles/${profile}" ] ; then
		profile="${bin_dir}/build_profiles/${profile}"
	else
		echo "Could not file $profile" 1>&2
		exit 1;
	fi
fi

echo "$(date -u "+%Y-%m-%d-%H.%M.%S") : ===== start tinder_build for branch $branch" | tee -a $logfile

if [ "x${pull}" == "xyes" ] ; then
	echo "$(date -u "+%Y-%m-%d-%H.%M.%S") : fresh git repos switch branch and rebase" | tee -a $logfile
	${bin_dir}/refresh_trees --source "${src}" --branch "${branch}"
	if [ "$?" == "1" ] ; then
		exit 1
	fi
fi

echo "$(date -u "+%Y-%m-%d-%H.%M.%S") : autogen and make" | tee -a $logfile

if [ "x${push_only}" == "xno" ] ; then
	result="--ko"
	${bin_dir}/daily_make -p ${profile} -t $(cat ${src}/pull.lastrun) -s ${src} && result="--ok"
else
	result="--ok"
fi

if [ "x${push}" == "xyes" ] ; then
	echo "$(date -u "+%Y-%m-%d-%H.%M.%S") : push the result to gmili" | tee -a $logfile
	${bin_dir}/daily_push -b "${branch}" -t $(cat ${src}/pull.lastrun) -s ${src} $result
fi
echo "$(date -u "+%Y-%m-%d-%H.%M.%S") : ===== done with result : $result" | tee -a $logfile
