#!/bin/bash

volume="${1}"

if [ -n "${volume}" ] ; then
   if [ -d "/Volumes/${volume}" ] ; then
       disk=$(df | grep "${volume}" | awk '{print $1}')
	   if [ -n "$disk" ] ; then
		   umount /Volumes/${volume}
		   hdiutil detach $disk
	   else
	       echo "no device found for volume ${volume}" >&2
		   exit 1
	   fi
   else
	   echo "mount point /Volumes/$volume is not a directory" >&2
	   exit 1;
   fi
else
	echo "missing argument: syntax is $0 <volume>" >&2
fi


